2019-12-04 20:50:15,683 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.7
2019-12-04 20:50:15,684 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'mpfconfigfile': '/usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2019-12-04-20-50-15-mpf-raspberrypi.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-12-04 20:50:15,684 : INFO : Machine : MPF path: /usr/local/lib/python3.7/dist-packages/mpf
2019-12-04 20:50:15,684 : INFO : Machine : Machine path: /home/pi/HotTipEM
2019-12-04 20:50:15,684 : INFO : Machine : Platform: linux
2019-12-04 20:50:15,684 : INFO : Machine : Python executable location: /usr/bin/python3
2019-12-04 20:50:15,685 : INFO : Machine : Python version: 3.7.3 (32-bit)
2019-12-04 20:50:15,685 : INFO : Machine : Machine config file #1: config.yaml
2019-12-04 20:50:15,687 : WARNING : ConfigProcessor : Config file in cache changed: /home/pi/HotTipEM/config/config.yaml
2019-12-04 20:50:15,687 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml.
2019-12-04 20:50:15,920 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml
2019-12-04 20:50:15,947 : INFO : ConfigProcessor : Loading config from file /home/pi/HotTipEM/config/config.yaml.
2019-12-04 20:50:15,974 : INFO : ConfigProcessor : Loading config: /home/pi/HotTipEM/config/config.yaml
2019-12-04 20:50:15,977 : ERROR : root : Error found in file /home/pi/HotTipEM/config/switches.yaml: Version mismatch. Expected: #config_version=5 Actual: #config_version5 Files: /home/pi/HotTipEM/config/switches.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/file_interfaces/yaml_interface.py", line 197, in load
    expected_version_str, version_str, filename))
AssertionError: Version mismatch. Expected: #config_version=5 Actual: #config_version5 Files: /home/pi/HotTipEM/config/switches.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/commands/game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 175, in __init__
    self._load_config()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 444, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_processor.py", line 163, in _load_config_file_and_return_loaded_files
    subconfig, subsubfiles = self._load_config_file_and_return_loaded_files(full_file, config_type)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "/usr/local/lib/python3.7/dist-packages/mpf/file_interfaces/yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file /home/pi/HotTipEM/config/switches.yaml: Version mismatch. Expected: #config_version=5 Actual: #config_version5 Files: /home/pi/HotTipEM/config/switches.yaml
