2019-12-04 20:51:35,758 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.7
2019-12-04 20:51:35,758 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'mpfconfigfile': '/usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2019-12-04-20-51-35-mpf-raspberrypi.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-12-04 20:51:35,758 : INFO : Machine : MPF path: /usr/local/lib/python3.7/dist-packages/mpf
2019-12-04 20:51:35,759 : INFO : Machine : Machine path: /home/pi/HotTipEM
2019-12-04 20:51:35,759 : INFO : Machine : Platform: linux
2019-12-04 20:51:35,759 : INFO : Machine : Python executable location: /usr/bin/python3
2019-12-04 20:51:35,759 : INFO : Machine : Python version: 3.7.3 (32-bit)
2019-12-04 20:51:35,759 : INFO : Machine : Machine config file #1: config.yaml
2019-12-04 20:51:35,761 : WARNING : ConfigProcessor : Config file in cache changed: /home/pi/HotTipEM/config/config.yaml
2019-12-04 20:51:35,761 : INFO : ConfigProcessor : Loading config from file /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml.
2019-12-04 20:51:35,987 : INFO : ConfigProcessor : Loading config: /usr/local/lib/python3.7/dist-packages/mpf/mpfconfig.yaml
2019-12-04 20:51:36,015 : INFO : ConfigProcessor : Loading config from file /home/pi/HotTipEM/config/config.yaml.
2019-12-04 20:51:36,041 : INFO : ConfigProcessor : Loading config: /home/pi/HotTipEM/config/config.yaml
2019-12-04 20:51:36,084 : ERROR : root : Error found in file /home/pi/HotTipEM/config/switches.yaml: 'Key "switches" was defined multiple times in config   in "/home/pi/HotTipEM/config/switches.yaml", line 68, column 1'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/file_interfaces/yaml_interface.py", line 198, in load
    config = self.process(f)
  File "/usr/local/lib/python3.7/dist-packages/mpf/file_interfaces/yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/constructor.py", line 114, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.7/dist-packages/ruamel/yaml/constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.7/dist-packages/mpf/file_interfaces/yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "switches" was defined multiple times in config   in "/home/pi/HotTipEM/config/switches.yaml", line 68, column 1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/commands/game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 175, in __init__
    self._load_config()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 444, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_processor.py", line 163, in _load_config_file_and_return_loaded_files
    subconfig, subsubfiles = self._load_config_file_and_return_loaded_files(full_file, config_type)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "/usr/local/lib/python3.7/dist-packages/mpf/file_interfaces/yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file /home/pi/HotTipEM/config/switches.yaml: 'Key "switches" was defined multiple times in config   in "/home/pi/HotTipEM/config/switches.yaml", line 68, column 1'
